replaceitem entity @s slot.inventory 0 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 1 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 2 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 3 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 4 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 5 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 6 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 7 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 8 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 9 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 10 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 11 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 12 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 13 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 14 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 15 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 16 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 17 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 18 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 19 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 20 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 21 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 22 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 23 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 24 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 25 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.inventory 26 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}

replaceitem entity @s slot.hotbar 0 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.hotbar 1 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.hotbar 2 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.hotbar 3 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.hotbar 4 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.hotbar 5 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.hotbar 6 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.hotbar 7 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.hotbar 8 leather_cap 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
replaceitem entity @s slot.weapon.offhand 0 leather_cap
